package ua.homework.testio.model;

import javax.persistence.*;
import java.util.Set;

/**
 * Created by Alex on 08.07.2016.
 */
@Entity
@Table(name = "courses")
@NamedQueries({@NamedQuery(name = "getAll", query = "SELECT c FROM Course c")})
public class Course extends IdAutoGeneratedEntity {

    @Column(nullable = false)
    private String title;

    private String Description;

    @ManyToOne
    @JoinColumn(name = "teacher_id", referencedColumnName = "id")
    private Teacher owner;

    //private Set<Student> students;

    public Course() {
    }

    public Course(String title, String description) {
        this.title = title;
        Description = description;
    }

    public Course(String title, String description, Teacher owner) {
        this.title = title;
        Description = description;
        this.owner = owner;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return Description;
    }

    public void setDescription(String description) {
        Description = description;
    }

    public Teacher getOwner() {
        return owner;
    }

    public void setOwner(Teacher owner) {
        this.owner = owner;
    }

  /*  public Set<Student> getStudents() {
        return students;
    }

    public void setStudents(Set<Student> students) {
        this.students = students;
    }*/

}
